# Generated by Django 3.2.4 on 2021-06-30 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(default='admin', max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('slug', models.SlugField(max_length=255)),
                ('stock', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='tienda.categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_producto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ('-creado',),
            },
            managers=[
                ('productos', django.db.models.manager.Manager()),
            ],
        ),
    ]
